Add tox testing, with code-quality tests
tlambert03/ome-types pull request #39
Opened 2020-09-07 16:03 UTC by tlambert03

use tox for testing
remove pytest model fixture
remove autogen from wheel
add flake8 checks
add autoflake formatting to generated code

2020-09-07 17:08 UTC, tlambert03 commented
@jmuhlich, you'll notice I had to add "mapannotation" back to the `SHOULD_FAIL` list.  here's the error I'm getting (in `OME.__post_init_post_parse__`)... not sure if it's related to the removal of the test fixture?:


```pytb
_____________________________________________ test_convert_schema[mapannotation] _____________________________________________

xml = PosixPath('/Users/talley/Dropbox (HMS)/Python/ome-types/testing/data/mapannotation.ome.xml')

    @pytest.mark.parametrize("xml", params, ids=true_stem)
    def test_convert_schema(xml):

        if true_stem(xml) in SHOULD_RAISE:
            with pytest.raises(XMLSchemaValidationError):
                assert from_xml(xml)
        else:
>           assert from_xml(xml)

testing/test_model.py:43:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/private/tmp/.tox/py38/lib/python3.8/site-packages/ome_types/__init__.py:30: in from_xml
    return OME(**d)  # type: ignore
<string>:19: in __init__
    ???
pydantic/dataclasses.py:86: in pydantic.dataclasses._process_class._pydantic_post_init
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = OME(images=[<1 Images>]), args = ()
ids = {'Image:0': Image(
   id='Image:0',
   name='6x6x1x8-swatch.tif',
   pixels=Pixels(
      id='Pixels:0:0',
      dimen...4,
   size_z=1,
   type='uint8',
   bin_data=[<1 Bin_Data>],
   physical_size_x=10000.0,
   physical_size_y=10000.0,
)}
ref = AnnotationRef(id='Annotation:1')

    def __post_init_post_parse__(self: Any, *args: Any) -> None:
        ids = collect_ids(self)
        for ref in collect_references(self):
>           ref.ref_ = weakref.ref(ids[ref.id])
E           KeyError: 'Annotation:1'

/private/tmp/.tox/py38/lib/python3.8/site-packages/ome_types/model/ome.py:77: KeyError
```

2020-09-08 16:44 UTC, jmuhlich commented
Aha! I encountered that exact issue in the course of my xml-write work when running `from_xml` on that xml file interactively, but the test was still passing. I realized while running all the xml files through a read-write round trip that we never implemented MapAnnotation, which is why this test is failing. However I'm not yet sure why the previous test setup didn't fail here. I'm going to dig into it more today, but I'm guessing `OME.__post_init_post_parse__` is not being called in the fixture-based context for some reason.

2020-09-08 16:58 UTC, jmuhlich requested changes
Looks great! Only a few minor issues/questions.

2020-09-08 16:58 UTC, jmuhlich commented on src/ome_autogen.py
> +    from autoflake import fix_code
Is there a reason this import can't go at the top?

2020-09-08 16:58 UTC, jmuhlich commented on src/ome_types/__init__.py
> +    )
Add ` from None` at the end of this line to suppress the chained exception message output. When an `except` block raises an exception unintentionally you want to see the originating exception too, but we don't want  that here.

2020-09-08 16:58 UTC, jmuhlich commented on testing/test_autogen.py
> +    assert importlib.import_module(target_dir.name)
`test_model` feels like squatting on that top-level module name... maybe this could be `ome_types_test_model` to sort of namespace it more tightly? I know if a real `test_model` package was installed the `path.insert(0...)` would override it, but it still feels a little dirty.

2020-09-08 16:58 UTC, jmuhlich commented on setup.cfg
> +; py_modules = ome_autogen
delete line?

2020-09-08 17:04 UTC, jmuhlich commented
So if I understand this setup, we can still run `pytest` constantly for quick feedback when developing, and run `tox` less often for more complete isolated testing (like before committing).

2020-09-08 17:06 UTC, tlambert03 commented on setup.cfg
> +; py_modules = ome_autogen
sure... we'll probably never want to distribute that anymore right?

2020-09-08 17:07 UTC, tlambert03 commented on src/ome_autogen.py
> +    from autoflake import fix_code
none at all :) will do

2020-09-08 17:07 UTC, tlambert03 commented on src/ome_types/__init__.py
> +    )
good point

2020-09-08 17:09 UTC, tlambert03 commented
> So if I understand this setup, we can still run pytest constantly for quick feedback when developing, and run tox less often for more complete isolated testing (like before committing).

yep... and if you don't have a generated `model` module, then you'll just get that error reminding you to generate it

2020-09-08 17:13 UTC, tlambert03 commented
also, an important setting in the tox config here is `isolated_build = True` ... which makes sure it builds the full package in the tox environment, and doesn't overwrite the current model code

2020-09-08 17:21 UTC, tlambert03 commented
I forgot to point out, that I added a flake8 lint CI check here, but _haven't_ actually added any `pre-commit` tooling.  which is likely going to be very annoying.  Any thoughts on that?  do you like using pre-commit and linters?  or should I just disabled that CI test?

2020-09-09 04:11 UTC, jmuhlich commented
What about arranging for Tox to run flake8 and mypy? And why not `black --check` while we're at it? Then we can just run `tox` once before commit and be fairly sure that CI won't find any unexpected problems.

Oh and I figured out the issue with the erroneously-passing `mapannotation` test case: It was the thing where the different instance of the model package breaks `isinstance`. Due to this, `util.collect_references` was unable to "see" the Reference instances. Now that the test uses the normal model package, isinstance works again and the dangling references are correctly detected.

2020-09-09 04:38 UTC, jmuhlich approved these changes
Looks good to me overall, I'll leave it up to you to decide how to handle the flake8 issue in the end.

2020-09-09 17:49 UTC, tlambert03 commented
> What about arranging for Tox to run flake8 and mypy? And why not black --check while we're at it? Then we can just run tox once before commit and be fairly sure that CI won't find any unexpected problems.

ok, I quite like having `pre-commit` in other projects... so I added that here, and also use it to run all the checks in tox.  If you'd like, you can install pre-commit into your local environment to make sure code will pass checks before you commit.
 
```python
pip install pre-commit
pre-commit install
```

that's optional though... you can also just run `tox` before pushing... which will run `pre-commit run --all-files` in addition to testing.

2020-09-09 17:50 UTC, merged